package sop_corba;


/**
* sop_corba/ControladorCancionIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 22 de julio de 2022 04:20:44 PM COT
*/

public interface ControladorCancionIntOperations 
{
  boolean registrarCancion (sop_corba.ControladorCancionIntPackage.CancionDTO objCancion);
  sop_corba.ControladorCancionIntPackage.CancionDTO[] listarCanciones ();
} // interface ControladorCancionIntOperations
