package sop_corba;


/**
* sop_corba/ControladorCancionInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 22 de julio de 2022 04:20:43 PM COT
*/

public interface ControladorCancionInt extends ControladorCancionIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControladorCancionInt
