package sop_corba.ControladorNotificacionesIntPackage;

/**
* sop_corba/ControladorNotificacionesIntPackage/NotificacionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 4 de agosto de 2022 11:52:15 AM COT
*/

public final class NotificacionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO value = null;

  public NotificacionDTOHolder ()
  {
  }

  public NotificacionDTOHolder (sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorNotificacionesIntPackage.NotificacionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorNotificacionesIntPackage.NotificacionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorNotificacionesIntPackage.NotificacionDTOHelper.type ();
  }

}
