package sop_corba;


/**
* sop_corba/ControladorNotificacionesIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 4 de agosto de 2022 11:52:15 AM COT
*/

public interface ControladorNotificacionesIntOperations 
{
  void registrarNotificacion (sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO objNotificacion);
} // interface ControladorNotificacionesIntOperations
