package sop_corba.ControladorNotificacionesIntPackage;


/**
* sop_corba/ControladorNotificacionesIntPackage/NotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 4 de agosto de 2022 11:52:15 AM COT
*/

public final class NotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String Id = null;
  public String TipoIdentificacion = null;
  public double ValorCompra = (double)0;
  public String LugarCompra = null;
  public String FechaHora = null;
  public String MedioPago = null;
  public String NitEmpresa = null;

  public NotificacionDTO ()
  {
  } // ctor

  public NotificacionDTO (String _Id, String _TipoIdentificacion, double _ValorCompra, String _LugarCompra, String _FechaHora, String _MedioPago, String _NitEmpresa)
  {
    Id = _Id;
    TipoIdentificacion = _TipoIdentificacion;
    ValorCompra = _ValorCompra;
    LugarCompra = _LugarCompra;
    FechaHora = _FechaHora;
    MedioPago = _MedioPago;
    NitEmpresa = _NitEmpresa;
  } // ctor

} // class NotificacionDTO
